export const aespaMembers = ['karina', 'giselle', 'winter', 'ningning'];

export const twiceMembers = [
	'nayeon',
	'jeongyeon',
	'momo',
	'sana',
	'jihyo',
	'mina',
	'dahyun',
	'chaeyoung',
	'tzuyu',
];

export const redVelvetMembers = ['irene', 'wendy', 'seulgi', 'joy', 'yeri'];

export const itzyMembers = ['yeji', 'lia', 'ryujin', 'chaeryeong', 'yuna'];

export const twiceSongs = [
	'1 to 10',
	'1, 3, 2',
	'21:29',
	'24/7',
	'after moon',
	'alcohol-free',
	'baby blue love',
	'basics',
	'battitude',
	'bdz',
	'be as one',
	'be ok',
	'behind the mask',
	'believer',
	'better',
	'beyond the horizon',
	'bitter sweet',
	'blame it on me',
	'blind in love',
	'bloom',
	'brand new girl',
	'brave',
	'breakthrough',
	'bring it back',
	'cactus',
	'candy boy',
	'candy pop',
	'candy',
	'catch a wave',
	'celebrate',
	'changing!',
	'cheer up',
	'chillax',
	'conversation',
	'crazy stupid love',
	'cruel',
	'cry for me',
	'dance again',
	'dance the night away',
	'dat ahh dat ooh',
	'deja vu',
	'depend on you',
	'ding dong',
	'dive',
	'do it again',
	'do what we like',
	'doughnut',
	'echoes of heart',
	'enemy',
	'espresso',
	'eye eye eyes',
	'f.i.l.a.',
	'fake & true',
	'fancy',
	'fanfare',
	'feel special',
	'ffw',
	'fine',
	'firework',
	'first time',
	'flow like waves',
	'four-leaf clover',
	'four',
	'g.o.a.t.',
	'get loud',
	'girls like us',
	'glow',
	'go hard',
	'going crazy',
	'gone',
	'good at love',
	'got the thrills',
	'handle it',
	'happy happy',
	'hare hare',
	'heart shaker',
	'heartbreak avenue',
	'hell in heaven',
	'hello',
	'here i am',
	'hi hello',
	'ho!',
	'hold me tight',
	'hot',
	'i got you',
	'i love you more than anyone',
	'i want you back',
	'ice cream',
	'icon',
	'in the summer',
	'inside of me',
	'jaljayo good night',
	'jelly jelly',
	'just be yourself',
	'keeper',
	'kiss my troubles away',
	'knock knock',
	'kura kura',
	'l.o.v.e.',
	'lalala',
	'last waltz',
	'let love go',
	'like 1',
	'like a fool',
	'like it like it',
	'like ooh-ahh',
	'likey',
	'look at me',
	'love foolish',
	'love is more',
	'love line',
	'love warning',
	'luv me',
	'magical',
	'make me go',
	'mamushi',
	'mars',
	'me+you',
	'merry & happy',
	'missing u',
	'moonlight sunrise',
	'moonlight',
	'more & more',
	'my headphones on',
	'new new',
	'next page',
	'ocean deep',
	'one day',
	'one in a million',
	'one more time',
	'one spark',
	'only you',
	'options',
	'oxygen',
	'peach gelato',
	'peach soda',
	'perfect world',
	'pieces of love',
	'pink lemonade',
	'pit-a-pat',
	'polish',
	'ponytail',
	'precious love',
	'promise',
	'push & pull',
	'queen of hearts',
	'queen',
	'rainbow',
	'real you',
	'rewind',
	'right hand girl',
	'rush',
	'sandcastle',
	'say it again',
	'say something',
	'say yes',
	'say you love me',
	'scandal',
	'scientist',
	'scorpion',
	'seesaw',
	'set me free',
	'shadow',
	'shot clock',
	'shot thru the heart',
	'signal',
	'someone like me',
	'sos',
	'stay by my side',
	'strategy',
	'strawberry moon',
	'strawberry',
	'stronger',
	'stuck in my head',
	'stuck',
	'sunset',
	'superstars',
	'sweet summer day',
	'sweet talker',
	'sweetest obsession',
	'swing',
	'takedown',
	'talk that talk',
	'talk',
	'thank you, family',
	'the best thing i ever did',
	'the feels',
	'the reason why',
	'the wish',
	'this is for',
	'three times a day',
	'tick tock',
	'touchdown',
	'trick it',
	'trouble',
	'truth',
	'tt',
	'tuk tok',
	'turn it up',
	'turtle',
	'up no more',
	'up to you',
	'voices of delight',
	'wake me up',
	'wallflower',
	'we pray',
	'what is love',
	'what you waiting for',
	'when we were kids',
	'wishing',
	'wonderful day',
	'woohoo',
	'wow',
	'yes or yes',
	'you get me',
	'you in my heart',
	'young & wild',
	"don't call me again",
	"don't give up",
	"how u doin'",
	"i can't stop me",
	"i'll show you",
	"i'm gonna be a star",
	"rollin'",
	"that's all i'm saying",
];
