export const biomes = [
	'ocean',
	'deep ocean',
	'warm ocean',
	'lukewarm ocean',
	'deep lukewarm ocean',
	'cold ocean',
	'deep cold ocean',
	'frozen ocean',
	'deep frozen ocean',
	'mushroom fields',
	'jagged peaks',
	'frozen peaks',
	'stony peaks',
	'meadow',
	'cherry grove',
	'grove',
	'snowy slopes',
	'windswept hills',
	'windswept gravelly hills',
	'windswept forest',
	'forest',
	'flower forest',
	'taiga',
	'old growth pine taiga',
	'old growth spruce taiga',
	'snowy taiga',
	'birch forest',
	'old growth birch forest',
	'dark forest',
	'pale garden',
	'jungle',
	'sparse jungle',
	'bamboo jungle',
	'dappled forest',
	'river',
	'frozen river',
	'swamp',
	'mangrove swamp',
	'beach',
	'snowy beach',
	'stony shore',
	'plains',
	'sunflower plains',
	'snowy plains',
	'ice spikes',
	'desert',
	'savanna',
	'savanna plateau',
	'windswept savanna',
	'badlands',
	'wooded badlands',
	'eroded badlands',
	'deep dark',
	'dripstone caves',
	'lush caves',
	'sulfur caves',
	'the void',
	'nether wastes',
	'soul sand valley',
	'crimson forest',
	'warped forest',
	'basalt deltas',
	'the end',
	'small end islands',
	'end midlands',
	'end highlands',
	'end barrens',
];

export const passiveMobs = [
	'allay',
	'armadillo',
	'axolotl',
	'bat',
	'camel',
	'camel husk',
	'cat',
	'chicken',
	'cod',
	'copper golem',
	'cow',
	'donkey',
	'frog',
	'glow squid',
	'happy ghast',
	'horse',
	'mooshroom',
	'mule',
	'ocelot',
	'parrot',
	'pig',
	'rabbit',
	'salmon',
	'sheep',
	'skeleton horse',
	'sniffer',
	'snow golem',
	'squid',
	'strider',
	'sulfur cube',
	'tadpole',
	'tropical fish',
	'turtle',
	'villager',
	'wandering trader',
	'zombie horse',
];

export const neutralMobs = [
	'bee',
	'cave spider',
	'dolphin',
	'drowned',
	'enderman',
	'fox',
	'goat',
	'iron golem',
	'llama',
	'nautilus',
	'panda',
	'piglin',
	'polar bear',
	'pufferfish',
	'spider',
	'trader llama',
	'wolf',
	'zombie nautilus',
	'zombified piglin',
];

export const hostileMobs = [
	'blaze',
	'bogged',
	'breeze',
	'creaking',
	'creeper',
	'elder guardian',
	'endermite',
	'evoker',
	'ghast',
	'guardian',
	'hoglin',
	'husk',
	'magma cube',
	'parched',
	'phantom',
	'piglin brute',
	'pillager',
	'ravager',
	'shulker',
	'silverfish',
	'skeleton',
	'slime',
	'stray',
	'vex',
	'vindicator',
	'warden',
	'witch',
	'wither skeleton',
	'zoglin',
	'zombie',
	'zombie villager',
	'ender dragon',
	'wither',
];

export const tools = [
	'flint and steel',
	'fishing rod',
	'diamond axe',
	'diamond pickaxe',
	'diamond hoe',
	'golden hoe',
	'stone hoe',
	'wooden hoe',
	'iron hoe',
	'iron pickaxe',
	'wooden shovel',
	'stone shovel',
	'iron shovel',
	'diamond shovel',
	'stone pickaxe',
	'wooden pickaxe',
	'wooden axe',
	'stone axe',
	'iron axe',
	'shears',
	'golden pickaxe',
	'golden shovel',
	'golden axe',
	'carrot on a stick',
	'warped fungus on a stick',
	'brush',
	'copper axe',
	'copper hoe',
	'copper pickaxe',
	'copper shovel',
	'shield',
	'bow',
	'crossbow',
	'mace',
	'wooden spear',
	'stone spear',
	'copper spear',
	'iron spear',
	'golden spear',
	'diamond spear',
	'netherite spear',
	'wooden sword',
	'stone sword',
	'copper sword',
	'iron sword',
	'golden sword',
	'diamond sword',
	'netherite sword',
	'netherite axe',
	'netherite hoe',
	'netherite pickaxe',
	'netherite shovel',
];
